apiVersion: v1
kind: Service
metadata:
  name: login-service
  labels:
    name: login-service
    app: invitation-card
spec:
  type: NodePort
  ports:
    - targetPort: 3000
      port: 3000
      nodePort: 30002
  selector:
    type: back-end
    app: invitation-card

