apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-deployment
  labels:
    app: invitation-card 
spec:
  selector:
    matchLabels:
      app: invitation-card
      type: back-end
  replicas: 2
  template:
    metadata:
      name: login-pod
      labels:
        app: invitation-card
        type: back-end
    spec:
      containers:
        - name: login-container
          image: pokhari7353/login:v2


